### ISSUE TITLE
acquire paper

### ISSUE THREAD

**Issue by pjw2146087** [duynamrcv/uav_multihop_adhoc#1]
hello, l have a great interest in your study and think it is a wonderful work， but l can't find it on many platforms such as google scholar. can you share the paper file with me？thank you.
Email:260017926@qq.com

**Comment by 7keqi** [comment]
hello, l am so exited to see such a good project， but l can't find it on many platforms . can you share the paper file with me？thank you very much.I am sorry to bother you.
Email:1325030377@qq.com

**Comment by duynamrcv** [comment]
sorry for the inconvenience, the paper is now available for everyone is [here](https://github.com/duynamrcv/uav_multihop_adhoc/blob/master/doc/2022_ICCAIS.pdf).

**Comment by pjw2146087** [comment]
> sorry for the inconvenience, the paper is now available for everyone is [here](https://github.com/duynamrcv/uav_multihop_adhoc/blob/master/doc/2022_ICCAIS.pdf).

Thank you very much
